// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.27.2
// source: mcp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_USER             Role = 1
	Role_ASSISTANT        Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "USER",
		2: "ASSISTANT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"USER":             1,
		"ASSISTANT":        2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

type InitializeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	Capabilities    *ClientCapabilities    `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	ClientInfo      *Implementation        `protobuf:"bytes,3,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeRequest) GetCapabilities() *ClientCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InitializeRequest) GetClientInfo() *Implementation {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type InitializeResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	Capabilities    *ServerCapabilities    `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	ServerInfo      *Implementation        `protobuf:"bytes,3,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	Instructions    *string                `protobuf:"bytes,4,opt,name=instructions,proto3,oneof" json:"instructions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	mi := &file_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResult) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeResult) GetCapabilities() *ServerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InitializeResult) GetServerInfo() *Implementation {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *InitializeResult) GetInstructions() string {
	if x != nil && x.Instructions != nil {
		return *x.Instructions
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,2,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ListToolsRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ListToolsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=nextCursor,proto3,oneof" json:"nextCursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResult) Reset() {
	*x = ListToolsResult{}
	mi := &file_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResult) ProtoMessage() {}

func (x *ListToolsResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResult.ProtoReflect.Descriptor instead.
func (*ListToolsResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResult) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ListToolsResult) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *ListToolsResult) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type CallToolRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     map[string]*structpb.Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XMeta         *structpb.Struct           `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArguments() map[string]*structpb.Value {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CallToolRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type CallToolResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Content           []*ContentBlock        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	StructuredContent *structpb.Struct       `protobuf:"bytes,2,opt,name=structuredContent,proto3,oneof" json:"structuredContent,omitempty"`
	IsError           *bool                  `protobuf:"varint,3,opt,name=isError,proto3,oneof" json:"isError,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CallToolResult) Reset() {
	*x = CallToolResult{}
	mi := &file_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResult) ProtoMessage() {}

func (x *CallToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResult.ProtoReflect.Descriptor instead.
func (*CallToolResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *CallToolResult) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CallToolResult) GetStructuredContent() *structpb.Struct {
	if x != nil {
		return x.StructuredContent
	}
	return nil
}

func (x *CallToolResult) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *PromptReference       `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Argument      *CompletionArgument    `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	Context       *CompletionContext     `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteRequest) GetRef() *PromptReference {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *CompleteRequest) GetArgument() *CompletionArgument {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *CompleteRequest) GetContext() *CompletionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CompleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completion    *Completion            `protobuf:"bytes,1,opt,name=completion,proto3" json:"completion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResult) Reset() {
	*x = CompleteResult{}
	mi := &file_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResult) ProtoMessage() {}

func (x *CompleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResult.ProtoReflect.Descriptor instead.
func (*CompleteResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteResult) GetCompletion() *Completion {
	if x != nil {
		return x.Completion
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_mcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{8}
}

type PingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_mcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{9}
}

type ListPromptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,2,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	mi := &file_mcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{10}
}

func (x *ListPromptsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ListPromptsRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ListPromptsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompts       []*Prompt              `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=nextCursor,proto3,oneof" json:"nextCursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsResult) Reset() {
	*x = ListPromptsResult{}
	mi := &file_mcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsResult) ProtoMessage() {}

func (x *ListPromptsResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsResult.ProtoReflect.Descriptor instead.
func (*ListPromptsResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{11}
}

func (x *ListPromptsResult) GetPrompts() []*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *ListPromptsResult) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *ListPromptsResult) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type GetPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,2,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	mi := &file_mcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{12}
}

func (x *GetPromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPromptRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type GetPromptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,2,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptResult) Reset() {
	*x = GetPromptResult{}
	mi := &file_mcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptResult) ProtoMessage() {}

func (x *GetPromptResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptResult.ProtoReflect.Descriptor instead.
func (*GetPromptResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{13}
}

func (x *GetPromptResult) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *GetPromptResult) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type Prompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       []*ContentBlock        `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	Params        map[string]*JSONSchema `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XMeta         *structpb.Struct       `protobuf:"bytes,5,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_mcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{14}
}

func (x *Prompt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prompt) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Prompt) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Prompt) GetParams() map[string]*JSONSchema {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Prompt) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ClientCapabilities struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Experimental  map[string]*structpb.Struct `protobuf:"bytes,1,rep,name=experimental,proto3" json:"experimental,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Roots         *RootsCapability            `protobuf:"bytes,2,opt,name=roots,proto3" json:"roots,omitempty"`
	Sampling      *structpb.Struct            `protobuf:"bytes,3,opt,name=sampling,proto3" json:"sampling,omitempty"`
	Elicitation   *structpb.Struct            `protobuf:"bytes,4,opt,name=elicitation,proto3" json:"elicitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCapabilities) Reset() {
	*x = ClientCapabilities{}
	mi := &file_mcp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCapabilities) ProtoMessage() {}

func (x *ClientCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCapabilities.ProtoReflect.Descriptor instead.
func (*ClientCapabilities) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{15}
}

func (x *ClientCapabilities) GetExperimental() map[string]*structpb.Struct {
	if x != nil {
		return x.Experimental
	}
	return nil
}

func (x *ClientCapabilities) GetRoots() *RootsCapability {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ClientCapabilities) GetSampling() *structpb.Struct {
	if x != nil {
		return x.Sampling
	}
	return nil
}

func (x *ClientCapabilities) GetElicitation() *structpb.Struct {
	if x != nil {
		return x.Elicitation
	}
	return nil
}

type ServerCapabilities struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Experimental  map[string]*structpb.Struct `protobuf:"bytes,1,rep,name=experimental,proto3" json:"experimental,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Logging       *structpb.Struct            `protobuf:"bytes,2,opt,name=logging,proto3" json:"logging,omitempty"`
	Completions   *structpb.Struct            `protobuf:"bytes,3,opt,name=completions,proto3" json:"completions,omitempty"`
	Prompts       *PromptsCapability          `protobuf:"bytes,4,opt,name=prompts,proto3" json:"prompts,omitempty"`
	Resources     *ResourcesCapability        `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Tools         *ToolsCapability            `protobuf:"bytes,6,opt,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCapabilities) Reset() {
	*x = ServerCapabilities{}
	mi := &file_mcp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCapabilities) ProtoMessage() {}

func (x *ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCapabilities.ProtoReflect.Descriptor instead.
func (*ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{16}
}

func (x *ServerCapabilities) GetExperimental() map[string]*structpb.Struct {
	if x != nil {
		return x.Experimental
	}
	return nil
}

func (x *ServerCapabilities) GetLogging() *structpb.Struct {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *ServerCapabilities) GetCompletions() *structpb.Struct {
	if x != nil {
		return x.Completions
	}
	return nil
}

func (x *ServerCapabilities) GetPrompts() *PromptsCapability {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *ServerCapabilities) GetResources() *ResourcesCapability {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ServerCapabilities) GetTools() *ToolsCapability {
	if x != nil {
		return x.Tools
	}
	return nil
}

type RootsCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListChanged   *bool                  `protobuf:"varint,1,opt,name=listChanged,proto3,oneof" json:"listChanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootsCapability) Reset() {
	*x = RootsCapability{}
	mi := &file_mcp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootsCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootsCapability) ProtoMessage() {}

func (x *RootsCapability) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootsCapability.ProtoReflect.Descriptor instead.
func (*RootsCapability) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{17}
}

func (x *RootsCapability) GetListChanged() bool {
	if x != nil && x.ListChanged != nil {
		return *x.ListChanged
	}
	return false
}

type PromptsCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListChanged   *bool                  `protobuf:"varint,1,opt,name=listChanged,proto3,oneof" json:"listChanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptsCapability) Reset() {
	*x = PromptsCapability{}
	mi := &file_mcp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptsCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptsCapability) ProtoMessage() {}

func (x *PromptsCapability) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptsCapability.ProtoReflect.Descriptor instead.
func (*PromptsCapability) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{18}
}

func (x *PromptsCapability) GetListChanged() bool {
	if x != nil && x.ListChanged != nil {
		return *x.ListChanged
	}
	return false
}

type ResourcesCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribe     *bool                  `protobuf:"varint,1,opt,name=subscribe,proto3,oneof" json:"subscribe,omitempty"`
	ListChanged   *bool                  `protobuf:"varint,2,opt,name=listChanged,proto3,oneof" json:"listChanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesCapability) Reset() {
	*x = ResourcesCapability{}
	mi := &file_mcp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesCapability) ProtoMessage() {}

func (x *ResourcesCapability) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesCapability.ProtoReflect.Descriptor instead.
func (*ResourcesCapability) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{19}
}

func (x *ResourcesCapability) GetSubscribe() bool {
	if x != nil && x.Subscribe != nil {
		return *x.Subscribe
	}
	return false
}

func (x *ResourcesCapability) GetListChanged() bool {
	if x != nil && x.ListChanged != nil {
		return *x.ListChanged
	}
	return false
}

type ToolsCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListChanged   *bool                  `protobuf:"varint,1,opt,name=listChanged,proto3,oneof" json:"listChanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsCapability) Reset() {
	*x = ToolsCapability{}
	mi := &file_mcp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsCapability) ProtoMessage() {}

func (x *ToolsCapability) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsCapability.ProtoReflect.Descriptor instead.
func (*ToolsCapability) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{20}
}

func (x *ToolsCapability) GetListChanged() bool {
	if x != nil && x.ListChanged != nil {
		return *x.ListChanged
	}
	return false
}

type Implementation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Implementation) Reset() {
	*x = Implementation{}
	mi := &file_mcp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Implementation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Implementation) ProtoMessage() {}

func (x *Implementation) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Implementation.ProtoReflect.Descriptor instead.
func (*Implementation) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{21}
}

func (x *Implementation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Implementation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Implementation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type BaseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMetadata) Reset() {
	*x = BaseMetadata{}
	mi := &file_mcp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMetadata) ProtoMessage() {}

func (x *BaseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMetadata.ProtoReflect.Descriptor instead.
func (*BaseMetadata) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{22}
}

func (x *BaseMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseMetadata) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	InputSchema   *JSONSchema            `protobuf:"bytes,4,opt,name=inputSchema,proto3" json:"inputSchema,omitempty"`
	OutputSchema  *JSONSchema            `protobuf:"bytes,5,opt,name=outputSchema,proto3,oneof" json:"outputSchema,omitempty"`
	Annotations   *ToolAnnotations       `protobuf:"bytes,6,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,7,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_mcp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{23}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Tool) GetInputSchema() *JSONSchema {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *Tool) GetOutputSchema() *JSONSchema {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *Tool) GetAnnotations() *ToolAnnotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Tool) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type JSONSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]*JSONSchema `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required      []string               `protobuf:"bytes,3,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONSchema) Reset() {
	*x = JSONSchema{}
	mi := &file_mcp_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONSchema) ProtoMessage() {}

func (x *JSONSchema) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONSchema.ProtoReflect.Descriptor instead.
func (*JSONSchema) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{24}
}

func (x *JSONSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JSONSchema) GetProperties() map[string]*JSONSchema {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *JSONSchema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

type ToolAnnotations struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ReadOnlyHint    *bool                  `protobuf:"varint,2,opt,name=readOnlyHint,proto3,oneof" json:"readOnlyHint,omitempty"`
	DestructiveHint *bool                  `protobuf:"varint,3,opt,name=destructiveHint,proto3,oneof" json:"destructiveHint,omitempty"`
	IdempotentHint  *bool                  `protobuf:"varint,4,opt,name=idempotentHint,proto3,oneof" json:"idempotentHint,omitempty"`
	OpenWorldHint   *bool                  `protobuf:"varint,5,opt,name=openWorldHint,proto3,oneof" json:"openWorldHint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolAnnotations) Reset() {
	*x = ToolAnnotations{}
	mi := &file_mcp_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolAnnotations) ProtoMessage() {}

func (x *ToolAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolAnnotations.ProtoReflect.Descriptor instead.
func (*ToolAnnotations) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{25}
}

func (x *ToolAnnotations) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ToolAnnotations) GetReadOnlyHint() bool {
	if x != nil && x.ReadOnlyHint != nil {
		return *x.ReadOnlyHint
	}
	return false
}

func (x *ToolAnnotations) GetDestructiveHint() bool {
	if x != nil && x.DestructiveHint != nil {
		return *x.DestructiveHint
	}
	return false
}

func (x *ToolAnnotations) GetIdempotentHint() bool {
	if x != nil && x.IdempotentHint != nil {
		return *x.IdempotentHint
	}
	return false
}

func (x *ToolAnnotations) GetOpenWorldHint() bool {
	if x != nil && x.OpenWorldHint != nil {
		return *x.OpenWorldHint
	}
	return false
}

type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ContentType:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	//	*ContentBlock_Audio
	//	*ContentBlock_ResourceLink
	//	*ContentBlock_EmbeddedResource
	ContentType   isContentBlock_ContentType `protobuf_oneof:"content_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_mcp_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{26}
}

func (x *ContentBlock) GetContentType() isContentBlock_ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *ContentBlock) GetText() *TextContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlock) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentBlock) GetAudio() *AudioContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ContentBlock) GetResourceLink() *ResourceLink {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_ResourceLink); ok {
			return x.ResourceLink
		}
	}
	return nil
}

func (x *ContentBlock) GetEmbeddedResource() *EmbeddedResource {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_EmbeddedResource); ok {
			return x.EmbeddedResource
		}
	}
	return nil
}

type isContentBlock_ContentType interface {
	isContentBlock_ContentType()
}

type ContentBlock_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type ContentBlock_Audio struct {
	Audio *AudioContent `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

type ContentBlock_ResourceLink struct {
	ResourceLink *ResourceLink `protobuf:"bytes,4,opt,name=resourceLink,proto3,oneof"`
}

type ContentBlock_EmbeddedResource struct {
	EmbeddedResource *EmbeddedResource `protobuf:"bytes,5,opt,name=embeddedResource,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_ContentType() {}

func (*ContentBlock_Image) isContentBlock_ContentType() {}

func (*ContentBlock_Audio) isContentBlock_ContentType() {}

func (*ContentBlock_ResourceLink) isContentBlock_ContentType() {}

func (*ContentBlock_EmbeddedResource) isContentBlock_ContentType() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,2,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_mcp_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{27}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *TextContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,3,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_mcp_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{28}
}

func (x *ImageContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ImageContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type AudioContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,3,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_mcp_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{29}
}

func (x *AudioContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AudioContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AudioContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ResourceLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Should always be "resource_link"
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLink) Reset() {
	*x = ResourceLink{}
	mi := &file_mcp_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLink) ProtoMessage() {}

func (x *ResourceLink) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLink.ProtoReflect.Descriptor instead.
func (*ResourceLink) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{30}
}

func (x *ResourceLink) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceLink) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type EmbeddedResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Should always be "resource"
	// Types that are valid to be assigned to ResourceContents:
	//
	//	*EmbeddedResource_TextResource
	//	*EmbeddedResource_BlobResource
	ResourceContents isEmbeddedResource_ResourceContents `protobuf_oneof:"resource_contents"`
	Annotations      *Annotations                        `protobuf:"bytes,4,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta            *structpb.Struct                    `protobuf:"bytes,5,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmbeddedResource) Reset() {
	*x = EmbeddedResource{}
	mi := &file_mcp_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedResource) ProtoMessage() {}

func (x *EmbeddedResource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedResource.ProtoReflect.Descriptor instead.
func (*EmbeddedResource) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{31}
}

func (x *EmbeddedResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmbeddedResource) GetResourceContents() isEmbeddedResource_ResourceContents {
	if x != nil {
		return x.ResourceContents
	}
	return nil
}

func (x *EmbeddedResource) GetTextResource() *TextResourceContents {
	if x != nil {
		if x, ok := x.ResourceContents.(*EmbeddedResource_TextResource); ok {
			return x.TextResource
		}
	}
	return nil
}

func (x *EmbeddedResource) GetBlobResource() *BlobResourceContents {
	if x != nil {
		if x, ok := x.ResourceContents.(*EmbeddedResource_BlobResource); ok {
			return x.BlobResource
		}
	}
	return nil
}

func (x *EmbeddedResource) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *EmbeddedResource) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type isEmbeddedResource_ResourceContents interface {
	isEmbeddedResource_ResourceContents()
}

type EmbeddedResource_TextResource struct {
	TextResource *TextResourceContents `protobuf:"bytes,2,opt,name=textResource,proto3,oneof"`
}

type EmbeddedResource_BlobResource struct {
	BlobResource *BlobResourceContents `protobuf:"bytes,3,opt,name=blobResource,proto3,oneof"`
}

func (*EmbeddedResource_TextResource) isEmbeddedResource_ResourceContents() {}

func (*EmbeddedResource_BlobResource) isEmbeddedResource_ResourceContents() {}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	MimeType      *string                `protobuf:"bytes,5,opt,name=mimeType,proto3,oneof" json:"mimeType,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,6,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	Size          *int64                 `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,8,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_mcp_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{32}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Resource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Resource) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *Resource) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Resource) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Resource) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type TextResourceContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	MimeType      *string                `protobuf:"bytes,2,opt,name=mimeType,proto3,oneof" json:"mimeType,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResourceContents) Reset() {
	*x = TextResourceContents{}
	mi := &file_mcp_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResourceContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResourceContents) ProtoMessage() {}

func (x *TextResourceContents) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResourceContents.ProtoReflect.Descriptor instead.
func (*TextResourceContents) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{33}
}

func (x *TextResourceContents) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TextResourceContents) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *TextResourceContents) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResourceContents) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type BlobResourceContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	MimeType      *string                `protobuf:"bytes,2,opt,name=mimeType,proto3,oneof" json:"mimeType,omitempty"`
	Blob          []byte                 `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobResourceContents) Reset() {
	*x = BlobResourceContents{}
	mi := &file_mcp_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobResourceContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobResourceContents) ProtoMessage() {}

func (x *BlobResourceContents) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobResourceContents.ProtoReflect.Descriptor instead.
func (*BlobResourceContents) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{34}
}

func (x *BlobResourceContents) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *BlobResourceContents) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *BlobResourceContents) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *BlobResourceContents) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type Annotations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      []Role                 `protobuf:"varint,1,rep,packed,name=audience,proto3,enum=mcp.Role" json:"audience,omitempty"`
	Priority      *float32               `protobuf:"fixed32,2,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	LastModified  *string                `protobuf:"bytes,3,opt,name=lastModified,proto3,oneof" json:"lastModified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotations) Reset() {
	*x = Annotations{}
	mi := &file_mcp_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotations) ProtoMessage() {}

func (x *Annotations) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotations.ProtoReflect.Descriptor instead.
func (*Annotations) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{35}
}

func (x *Annotations) GetAudience() []Role {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *Annotations) GetPriority() float32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *Annotations) GetLastModified() string {
	if x != nil && x.LastModified != nil {
		return *x.LastModified
	}
	return ""
}

type Reference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RefOneof:
	//
	//	*Reference_Prompt
	//	*Reference_ResourceTemplate
	RefOneof      isReference_RefOneof `protobuf_oneof:"ref_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_mcp_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{36}
}

func (x *Reference) GetRefOneof() isReference_RefOneof {
	if x != nil {
		return x.RefOneof
	}
	return nil
}

func (x *Reference) GetPrompt() *PromptReference {
	if x != nil {
		if x, ok := x.RefOneof.(*Reference_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *Reference) GetResourceTemplate() *ResourceTemplateReference {
	if x != nil {
		if x, ok := x.RefOneof.(*Reference_ResourceTemplate); ok {
			return x.ResourceTemplate
		}
	}
	return nil
}

type isReference_RefOneof interface {
	isReference_RefOneof()
}

type Reference_Prompt struct {
	Prompt *PromptReference `protobuf:"bytes,1,opt,name=prompt,proto3,oneof"`
}

type Reference_ResourceTemplate struct {
	ResourceTemplate *ResourceTemplateReference `protobuf:"bytes,2,opt,name=resourceTemplate,proto3,oneof"`
}

func (*Reference_Prompt) isReference_RefOneof() {}

func (*Reference_ResourceTemplate) isReference_RefOneof() {}

type PromptReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptReference) Reset() {
	*x = PromptReference{}
	mi := &file_mcp_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptReference) ProtoMessage() {}

func (x *PromptReference) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptReference.ProtoReflect.Descriptor instead.
func (*PromptReference) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{37}
}

func (x *PromptReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromptReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceTemplateReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTemplateReference) Reset() {
	*x = ResourceTemplateReference{}
	mi := &file_mcp_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTemplateReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTemplateReference) ProtoMessage() {}

func (x *ResourceTemplateReference) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTemplateReference.ProtoReflect.Descriptor instead.
func (*ResourceTemplateReference) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{38}
}

func (x *ResourceTemplateReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceTemplateReference) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CompletionArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionArgument) Reset() {
	*x = CompletionArgument{}
	mi := &file_mcp_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionArgument) ProtoMessage() {}

func (x *CompletionArgument) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionArgument.ProtoReflect.Descriptor instead.
func (*CompletionArgument) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{39}
}

func (x *CompletionArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompletionArgument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CompletionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arguments     map[string]string      `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionContext) Reset() {
	*x = CompletionContext{}
	mi := &file_mcp_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionContext) ProtoMessage() {}

func (x *CompletionContext) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionContext.ProtoReflect.Descriptor instead.
func (*CompletionContext) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{40}
}

func (x *CompletionContext) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Total         *int64                 `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	HasMore       *bool                  `protobuf:"varint,3,opt,name=hasMore,proto3,oneof" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_mcp_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{41}
}

func (x *Completion) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Completion) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *Completion) GetHasMore() bool {
	if x != nil && x.HasMore != nil {
		return *x.HasMore
	}
	return false
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x03mcp\x1a\x1cgoogle/protobuf/struct.proto\"\xaf\x01\n" +
	"\x11InitializeRequest\x12(\n" +
	"\x0fprotocolVersion\x18\x01 \x01(\tR\x0fprotocolVersion\x12;\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x17.mcp.ClientCapabilitiesR\fcapabilities\x123\n" +
	"\n" +
	"clientInfo\x18\x03 \x01(\v2\x13.mcp.ImplementationR\n" +
	"clientInfo\"\xe8\x01\n" +
	"\x10InitializeResult\x12(\n" +
	"\x0fprotocolVersion\x18\x01 \x01(\tR\x0fprotocolVersion\x12;\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x17.mcp.ServerCapabilitiesR\fcapabilities\x123\n" +
	"\n" +
	"serverInfo\x18\x03 \x01(\v2\x13.mcp.ImplementationR\n" +
	"serverInfo\x12'\n" +
	"\finstructions\x18\x04 \x01(\tH\x00R\finstructions\x88\x01\x01B\x0f\n" +
	"\r_instructions\"w\n" +
	"\x10ListToolsRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\t\n" +
	"\a_cursorB\b\n" +
	"\x06X_meta\"\xa3\x01\n" +
	"\x0fListToolsResult\x12\x1f\n" +
	"\x05tools\x18\x01 \x03(\v2\t.mcp.ToolR\x05tools\x12#\n" +
	"\n" +
	"nextCursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\r\n" +
	"\v_nextCursorB\b\n" +
	"\x06X_meta\"\xfb\x01\n" +
	"\x0fCallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\targuments\x18\x02 \x03(\v2#.mcp.CallToolRequest.ArgumentsEntryR\targuments\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\x04Meta\x88\x01\x01\x1aT\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\b\n" +
	"\x06X_meta\"\xca\x01\n" +
	"\x0eCallToolResult\x12+\n" +
	"\acontent\x18\x01 \x03(\v2\x11.mcp.ContentBlockR\acontent\x12J\n" +
	"\x11structuredContent\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x11structuredContent\x88\x01\x01\x12\x1d\n" +
	"\aisError\x18\x03 \x01(\bH\x01R\aisError\x88\x01\x01B\x14\n" +
	"\x12_structuredContentB\n" +
	"\n" +
	"\b_isError\"\xa0\x01\n" +
	"\x0fCompleteRequest\x12&\n" +
	"\x03ref\x18\x01 \x01(\v2\x14.mcp.PromptReferenceR\x03ref\x123\n" +
	"\bargument\x18\x02 \x01(\v2\x17.mcp.CompletionArgumentR\bargument\x120\n" +
	"\acontext\x18\x03 \x01(\v2\x16.mcp.CompletionContextR\acontext\"A\n" +
	"\x0eCompleteResult\x12/\n" +
	"\n" +
	"completion\x18\x01 \x01(\v2\x0f.mcp.CompletionR\n" +
	"completion\"\r\n" +
	"\vPingRequest\"\f\n" +
	"\n" +
	"PingResult\"y\n" +
	"\x12ListPromptsRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\t\n" +
	"\a_cursorB\b\n" +
	"\x06X_meta\"\xab\x01\n" +
	"\x11ListPromptsResult\x12%\n" +
	"\aprompts\x18\x01 \x03(\v2\v.mcp.PromptR\aprompts\x12#\n" +
	"\n" +
	"nextCursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\r\n" +
	"\v_nextCursorB\b\n" +
	"\x06X_meta\"c\n" +
	"\x10GetPromptRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05_meta\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x04Meta\x88\x01\x01B\b\n" +
	"\x06X_meta\"s\n" +
	"\x0fGetPromptResult\x12#\n" +
	"\x06prompt\x18\x01 \x01(\v2\v.mcp.PromptR\x06prompt\x121\n" +
	"\x05_meta\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x04Meta\x88\x01\x01B\b\n" +
	"\x06X_meta\"\xa8\x02\n" +
	"\x06Prompt\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12+\n" +
	"\acontent\x18\x03 \x03(\v2\x11.mcp.ContentBlockR\acontent\x12/\n" +
	"\x06params\x18\x04 \x03(\v2\x17.mcp.Prompt.ParamsEntryR\x06params\x121\n" +
	"\x05_meta\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01\x1aJ\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.mcp.JSONSchemaR\x05value:\x028\x01B\b\n" +
	"\x06_titleB\b\n" +
	"\x06X_meta\"\xd9\x02\n" +
	"\x12ClientCapabilities\x12M\n" +
	"\fexperimental\x18\x01 \x03(\v2).mcp.ClientCapabilities.ExperimentalEntryR\fexperimental\x12*\n" +
	"\x05roots\x18\x02 \x01(\v2\x14.mcp.RootsCapabilityR\x05roots\x123\n" +
	"\bsampling\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bsampling\x129\n" +
	"\velicitation\x18\x04 \x01(\v2\x17.google.protobuf.StructR\velicitation\x1aX\n" +
	"\x11ExperimentalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\xc1\x03\n" +
	"\x12ServerCapabilities\x12M\n" +
	"\fexperimental\x18\x01 \x03(\v2).mcp.ServerCapabilities.ExperimentalEntryR\fexperimental\x121\n" +
	"\alogging\x18\x02 \x01(\v2\x17.google.protobuf.StructR\alogging\x129\n" +
	"\vcompletions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vcompletions\x120\n" +
	"\aprompts\x18\x04 \x01(\v2\x16.mcp.PromptsCapabilityR\aprompts\x126\n" +
	"\tresources\x18\x05 \x01(\v2\x18.mcp.ResourcesCapabilityR\tresources\x12*\n" +
	"\x05tools\x18\x06 \x01(\v2\x14.mcp.ToolsCapabilityR\x05tools\x1aX\n" +
	"\x11ExperimentalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"H\n" +
	"\x0fRootsCapability\x12%\n" +
	"\vlistChanged\x18\x01 \x01(\bH\x00R\vlistChanged\x88\x01\x01B\x0e\n" +
	"\f_listChanged\"J\n" +
	"\x11PromptsCapability\x12%\n" +
	"\vlistChanged\x18\x01 \x01(\bH\x00R\vlistChanged\x88\x01\x01B\x0e\n" +
	"\f_listChanged\"}\n" +
	"\x13ResourcesCapability\x12!\n" +
	"\tsubscribe\x18\x01 \x01(\bH\x00R\tsubscribe\x88\x01\x01\x12%\n" +
	"\vlistChanged\x18\x02 \x01(\bH\x01R\vlistChanged\x88\x01\x01B\f\n" +
	"\n" +
	"_subscribeB\x0e\n" +
	"\f_listChanged\"H\n" +
	"\x0fToolsCapability\x12%\n" +
	"\vlistChanged\x18\x01 \x01(\bH\x00R\vlistChanged\x88\x01\x01B\x0e\n" +
	"\f_listChanged\"c\n" +
	"\x0eImplementation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB\b\n" +
	"\x06_title\"G\n" +
	"\fBaseMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title\"\xfe\x02\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x121\n" +
	"\vinputSchema\x18\x04 \x01(\v2\x0f.mcp.JSONSchemaR\vinputSchema\x128\n" +
	"\foutputSchema\x18\x05 \x01(\v2\x0f.mcp.JSONSchemaH\x02R\foutputSchema\x88\x01\x01\x12;\n" +
	"\vannotations\x18\x06 \x01(\v2\x14.mcp.ToolAnnotationsH\x03R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\a \x01(\v2\x17.google.protobuf.StructH\x04R\x04Meta\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_outputSchemaB\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xcd\x01\n" +
	"\n" +
	"JSONSchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12?\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2\x1f.mcp.JSONSchema.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\brequired\x18\x03 \x03(\tR\brequired\x1aN\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.mcp.JSONSchemaR\x05value:\x028\x01\"\xb0\x02\n" +
	"\x0fToolAnnotations\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12'\n" +
	"\freadOnlyHint\x18\x02 \x01(\bH\x01R\freadOnlyHint\x88\x01\x01\x12-\n" +
	"\x0fdestructiveHint\x18\x03 \x01(\bH\x02R\x0fdestructiveHint\x88\x01\x01\x12+\n" +
	"\x0eidempotentHint\x18\x04 \x01(\bH\x03R\x0eidempotentHint\x88\x01\x01\x12)\n" +
	"\ropenWorldHint\x18\x05 \x01(\bH\x04R\ropenWorldHint\x88\x01\x01B\b\n" +
	"\x06_titleB\x0f\n" +
	"\r_readOnlyHintB\x12\n" +
	"\x10_destructiveHintB\x11\n" +
	"\x0f_idempotentHintB\x10\n" +
	"\x0e_openWorldHint\"\x9a\x02\n" +
	"\fContentBlock\x12&\n" +
	"\x04text\x18\x01 \x01(\v2\x10.mcp.TextContentH\x00R\x04text\x12)\n" +
	"\x05image\x18\x02 \x01(\v2\x11.mcp.ImageContentH\x00R\x05image\x12)\n" +
	"\x05audio\x18\x03 \x01(\v2\x11.mcp.AudioContentH\x00R\x05audio\x127\n" +
	"\fresourceLink\x18\x04 \x01(\v2\x11.mcp.ResourceLinkH\x00R\fresourceLink\x12C\n" +
	"\x10embeddedResource\x18\x05 \x01(\v2\x15.mcp.EmbeddedResourceH\x00R\x10embeddedResourceB\x0e\n" +
	"\fcontent_type\"\xa7\x01\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x127\n" +
	"\vannotations\x18\x02 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xc4\x01\n" +
	"\fImageContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bmimeType\x18\x02 \x01(\tR\bmimeType\x127\n" +
	"\vannotations\x18\x03 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xc4\x01\n" +
	"\fAudioContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bmimeType\x18\x02 \x01(\tR\bmimeType\x127\n" +
	"\vannotations\x18\x03 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"M\n" +
	"\fResourceLink\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12)\n" +
	"\bresource\x18\x02 \x01(\v2\r.mcp.ResourceR\bresource\"\xc3\x02\n" +
	"\x10EmbeddedResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12?\n" +
	"\ftextResource\x18\x02 \x01(\v2\x19.mcp.TextResourceContentsH\x00R\ftextResource\x12?\n" +
	"\fblobResource\x18\x03 \x01(\v2\x19.mcp.BlobResourceContentsH\x00R\fblobResource\x127\n" +
	"\vannotations\x18\x04 \x01(\v2\x10.mcp.AnnotationsH\x01R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x02R\x04Meta\x88\x01\x01B\x13\n" +
	"\x11resource_contentsB\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xe2\x02\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bmimeType\x18\x05 \x01(\tH\x02R\bmimeType\x88\x01\x01\x127\n" +
	"\vannotations\x18\x06 \x01(\v2\x10.mcp.AnnotationsH\x03R\vannotations\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\a \x01(\x03H\x04R\x04size\x88\x01\x01\x121\n" +
	"\x05_meta\x18\b \x01(\v2\x17.google.protobuf.StructH\x05R\x04Meta\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_mimeTypeB\x0e\n" +
	"\f_annotationsB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06X_meta\"\xa7\x01\n" +
	"\x14TextResourceContents\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1f\n" +
	"\bmimeType\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\v\n" +
	"\t_mimeTypeB\b\n" +
	"\x06X_meta\"\xa7\x01\n" +
	"\x14BlobResourceContents\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1f\n" +
	"\bmimeType\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x12\n" +
	"\x04blob\x18\x03 \x01(\fR\x04blob\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\v\n" +
	"\t_mimeTypeB\b\n" +
	"\x06X_meta\"\x9c\x01\n" +
	"\vAnnotations\x12%\n" +
	"\baudience\x18\x01 \x03(\x0e2\t.mcp.RoleR\baudience\x12\x1f\n" +
	"\bpriority\x18\x02 \x01(\x02H\x00R\bpriority\x88\x01\x01\x12'\n" +
	"\flastModified\x18\x03 \x01(\tH\x01R\flastModified\x88\x01\x01B\v\n" +
	"\t_priorityB\x0f\n" +
	"\r_lastModified\"\x96\x01\n" +
	"\tReference\x12.\n" +
	"\x06prompt\x18\x01 \x01(\v2\x14.mcp.PromptReferenceH\x00R\x06prompt\x12L\n" +
	"\x10resourceTemplate\x18\x02 \x01(\v2\x1e.mcp.ResourceTemplateReferenceH\x00R\x10resourceTemplateB\v\n" +
	"\tref_oneof\"9\n" +
	"\x0fPromptReference\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"A\n" +
	"\x19ResourceTemplateReference\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\">\n" +
	"\x12CompletionArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x96\x01\n" +
	"\x11CompletionContext\x12C\n" +
	"\targuments\x18\x01 \x03(\v2%.mcp.CompletionContext.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\n" +
	"Completion\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x12\x19\n" +
	"\x05total\x18\x02 \x01(\x03H\x00R\x05total\x88\x01\x01\x12\x1d\n" +
	"\ahasMore\x18\x03 \x01(\bH\x01R\ahasMore\x88\x01\x01B\b\n" +
	"\x06_totalB\n" +
	"\n" +
	"\b_hasMore*5\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tASSISTANT\x10\x022\xa2\x03\n" +
	"\x14ModelContextProtocol\x12;\n" +
	"\n" +
	"Initialize\x12\x16.mcp.InitializeRequest\x1a\x15.mcp.InitializeResult\x127\n" +
	"\n" +
	"CallMethod\x12\x14.mcp.CallToolRequest\x1a\x13.mcp.CallToolResult\x128\n" +
	"\tListTools\x12\x15.mcp.ListToolsRequest\x1a\x14.mcp.ListToolsResult\x12>\n" +
	"\vListPrompts\x12\x17.mcp.ListPromptsRequest\x1a\x16.mcp.ListPromptsResult\x128\n" +
	"\tGetPrompt\x12\x15.mcp.GetPromptRequest\x1a\x14.mcp.GetPromptResult\x125\n" +
	"\bComplete\x12\x14.mcp.CompleteRequest\x1a\x13.mcp.CompleteResult\x12)\n" +
	"\x04Ping\x12\x10.mcp.PingRequest\x1a\x0f.mcp.PingResultB\rZ\vgrpc2mcp/pbb\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_mcp_proto_goTypes = []any{
	(Role)(0),                         // 0: mcp.Role
	(*InitializeRequest)(nil),         // 1: mcp.InitializeRequest
	(*InitializeResult)(nil),          // 2: mcp.InitializeResult
	(*ListToolsRequest)(nil),          // 3: mcp.ListToolsRequest
	(*ListToolsResult)(nil),           // 4: mcp.ListToolsResult
	(*CallToolRequest)(nil),           // 5: mcp.CallToolRequest
	(*CallToolResult)(nil),            // 6: mcp.CallToolResult
	(*CompleteRequest)(nil),           // 7: mcp.CompleteRequest
	(*CompleteResult)(nil),            // 8: mcp.CompleteResult
	(*PingRequest)(nil),               // 9: mcp.PingRequest
	(*PingResult)(nil),                // 10: mcp.PingResult
	(*ListPromptsRequest)(nil),        // 11: mcp.ListPromptsRequest
	(*ListPromptsResult)(nil),         // 12: mcp.ListPromptsResult
	(*GetPromptRequest)(nil),          // 13: mcp.GetPromptRequest
	(*GetPromptResult)(nil),           // 14: mcp.GetPromptResult
	(*Prompt)(nil),                    // 15: mcp.Prompt
	(*ClientCapabilities)(nil),        // 16: mcp.ClientCapabilities
	(*ServerCapabilities)(nil),        // 17: mcp.ServerCapabilities
	(*RootsCapability)(nil),           // 18: mcp.RootsCapability
	(*PromptsCapability)(nil),         // 19: mcp.PromptsCapability
	(*ResourcesCapability)(nil),       // 20: mcp.ResourcesCapability
	(*ToolsCapability)(nil),           // 21: mcp.ToolsCapability
	(*Implementation)(nil),            // 22: mcp.Implementation
	(*BaseMetadata)(nil),              // 23: mcp.BaseMetadata
	(*Tool)(nil),                      // 24: mcp.Tool
	(*JSONSchema)(nil),                // 25: mcp.JSONSchema
	(*ToolAnnotations)(nil),           // 26: mcp.ToolAnnotations
	(*ContentBlock)(nil),              // 27: mcp.ContentBlock
	(*TextContent)(nil),               // 28: mcp.TextContent
	(*ImageContent)(nil),              // 29: mcp.ImageContent
	(*AudioContent)(nil),              // 30: mcp.AudioContent
	(*ResourceLink)(nil),              // 31: mcp.ResourceLink
	(*EmbeddedResource)(nil),          // 32: mcp.EmbeddedResource
	(*Resource)(nil),                  // 33: mcp.Resource
	(*TextResourceContents)(nil),      // 34: mcp.TextResourceContents
	(*BlobResourceContents)(nil),      // 35: mcp.BlobResourceContents
	(*Annotations)(nil),               // 36: mcp.Annotations
	(*Reference)(nil),                 // 37: mcp.Reference
	(*PromptReference)(nil),           // 38: mcp.PromptReference
	(*ResourceTemplateReference)(nil), // 39: mcp.ResourceTemplateReference
	(*CompletionArgument)(nil),        // 40: mcp.CompletionArgument
	(*CompletionContext)(nil),         // 41: mcp.CompletionContext
	(*Completion)(nil),                // 42: mcp.Completion
	nil,                               // 43: mcp.CallToolRequest.ArgumentsEntry
	nil,                               // 44: mcp.Prompt.ParamsEntry
	nil,                               // 45: mcp.ClientCapabilities.ExperimentalEntry
	nil,                               // 46: mcp.ServerCapabilities.ExperimentalEntry
	nil,                               // 47: mcp.JSONSchema.PropertiesEntry
	nil,                               // 48: mcp.CompletionContext.ArgumentsEntry
	(*structpb.Struct)(nil),           // 49: google.protobuf.Struct
	(*structpb.Value)(nil),            // 50: google.protobuf.Value
}
var file_mcp_proto_depIdxs = []int32{
	16, // 0: mcp.InitializeRequest.capabilities:type_name -> mcp.ClientCapabilities
	22, // 1: mcp.InitializeRequest.clientInfo:type_name -> mcp.Implementation
	17, // 2: mcp.InitializeResult.capabilities:type_name -> mcp.ServerCapabilities
	22, // 3: mcp.InitializeResult.serverInfo:type_name -> mcp.Implementation
	49, // 4: mcp.ListToolsRequest._meta:type_name -> google.protobuf.Struct
	24, // 5: mcp.ListToolsResult.tools:type_name -> mcp.Tool
	49, // 6: mcp.ListToolsResult._meta:type_name -> google.protobuf.Struct
	43, // 7: mcp.CallToolRequest.arguments:type_name -> mcp.CallToolRequest.ArgumentsEntry
	49, // 8: mcp.CallToolRequest._meta:type_name -> google.protobuf.Struct
	27, // 9: mcp.CallToolResult.content:type_name -> mcp.ContentBlock
	49, // 10: mcp.CallToolResult.structuredContent:type_name -> google.protobuf.Struct
	38, // 11: mcp.CompleteRequest.ref:type_name -> mcp.PromptReference
	40, // 12: mcp.CompleteRequest.argument:type_name -> mcp.CompletionArgument
	41, // 13: mcp.CompleteRequest.context:type_name -> mcp.CompletionContext
	42, // 14: mcp.CompleteResult.completion:type_name -> mcp.Completion
	49, // 15: mcp.ListPromptsRequest._meta:type_name -> google.protobuf.Struct
	15, // 16: mcp.ListPromptsResult.prompts:type_name -> mcp.Prompt
	49, // 17: mcp.ListPromptsResult._meta:type_name -> google.protobuf.Struct
	49, // 18: mcp.GetPromptRequest._meta:type_name -> google.protobuf.Struct
	15, // 19: mcp.GetPromptResult.prompt:type_name -> mcp.Prompt
	49, // 20: mcp.GetPromptResult._meta:type_name -> google.protobuf.Struct
	27, // 21: mcp.Prompt.content:type_name -> mcp.ContentBlock
	44, // 22: mcp.Prompt.params:type_name -> mcp.Prompt.ParamsEntry
	49, // 23: mcp.Prompt._meta:type_name -> google.protobuf.Struct
	45, // 24: mcp.ClientCapabilities.experimental:type_name -> mcp.ClientCapabilities.ExperimentalEntry
	18, // 25: mcp.ClientCapabilities.roots:type_name -> mcp.RootsCapability
	49, // 26: mcp.ClientCapabilities.sampling:type_name -> google.protobuf.Struct
	49, // 27: mcp.ClientCapabilities.elicitation:type_name -> google.protobuf.Struct
	46, // 28: mcp.ServerCapabilities.experimental:type_name -> mcp.ServerCapabilities.ExperimentalEntry
	49, // 29: mcp.ServerCapabilities.logging:type_name -> google.protobuf.Struct
	49, // 30: mcp.ServerCapabilities.completions:type_name -> google.protobuf.Struct
	19, // 31: mcp.ServerCapabilities.prompts:type_name -> mcp.PromptsCapability
	20, // 32: mcp.ServerCapabilities.resources:type_name -> mcp.ResourcesCapability
	21, // 33: mcp.ServerCapabilities.tools:type_name -> mcp.ToolsCapability
	25, // 34: mcp.Tool.inputSchema:type_name -> mcp.JSONSchema
	25, // 35: mcp.Tool.outputSchema:type_name -> mcp.JSONSchema
	26, // 36: mcp.Tool.annotations:type_name -> mcp.ToolAnnotations
	49, // 37: mcp.Tool._meta:type_name -> google.protobuf.Struct
	47, // 38: mcp.JSONSchema.properties:type_name -> mcp.JSONSchema.PropertiesEntry
	28, // 39: mcp.ContentBlock.text:type_name -> mcp.TextContent
	29, // 40: mcp.ContentBlock.image:type_name -> mcp.ImageContent
	30, // 41: mcp.ContentBlock.audio:type_name -> mcp.AudioContent
	31, // 42: mcp.ContentBlock.resourceLink:type_name -> mcp.ResourceLink
	32, // 43: mcp.ContentBlock.embeddedResource:type_name -> mcp.EmbeddedResource
	36, // 44: mcp.TextContent.annotations:type_name -> mcp.Annotations
	49, // 45: mcp.TextContent._meta:type_name -> google.protobuf.Struct
	36, // 46: mcp.ImageContent.annotations:type_name -> mcp.Annotations
	49, // 47: mcp.ImageContent._meta:type_name -> google.protobuf.Struct
	36, // 48: mcp.AudioContent.annotations:type_name -> mcp.Annotations
	49, // 49: mcp.AudioContent._meta:type_name -> google.protobuf.Struct
	33, // 50: mcp.ResourceLink.resource:type_name -> mcp.Resource
	34, // 51: mcp.EmbeddedResource.textResource:type_name -> mcp.TextResourceContents
	35, // 52: mcp.EmbeddedResource.blobResource:type_name -> mcp.BlobResourceContents
	36, // 53: mcp.EmbeddedResource.annotations:type_name -> mcp.Annotations
	49, // 54: mcp.EmbeddedResource._meta:type_name -> google.protobuf.Struct
	36, // 55: mcp.Resource.annotations:type_name -> mcp.Annotations
	49, // 56: mcp.Resource._meta:type_name -> google.protobuf.Struct
	49, // 57: mcp.TextResourceContents._meta:type_name -> google.protobuf.Struct
	49, // 58: mcp.BlobResourceContents._meta:type_name -> google.protobuf.Struct
	0,  // 59: mcp.Annotations.audience:type_name -> mcp.Role
	38, // 60: mcp.Reference.prompt:type_name -> mcp.PromptReference
	39, // 61: mcp.Reference.resourceTemplate:type_name -> mcp.ResourceTemplateReference
	48, // 62: mcp.CompletionContext.arguments:type_name -> mcp.CompletionContext.ArgumentsEntry
	50, // 63: mcp.CallToolRequest.ArgumentsEntry.value:type_name -> google.protobuf.Value
	25, // 64: mcp.Prompt.ParamsEntry.value:type_name -> mcp.JSONSchema
	49, // 65: mcp.ClientCapabilities.ExperimentalEntry.value:type_name -> google.protobuf.Struct
	49, // 66: mcp.ServerCapabilities.ExperimentalEntry.value:type_name -> google.protobuf.Struct
	25, // 67: mcp.JSONSchema.PropertiesEntry.value:type_name -> mcp.JSONSchema
	1,  // 68: mcp.ModelContextProtocol.Initialize:input_type -> mcp.InitializeRequest
	5,  // 69: mcp.ModelContextProtocol.CallMethod:input_type -> mcp.CallToolRequest
	3,  // 70: mcp.ModelContextProtocol.ListTools:input_type -> mcp.ListToolsRequest
	11, // 71: mcp.ModelContextProtocol.ListPrompts:input_type -> mcp.ListPromptsRequest
	13, // 72: mcp.ModelContextProtocol.GetPrompt:input_type -> mcp.GetPromptRequest
	7,  // 73: mcp.ModelContextProtocol.Complete:input_type -> mcp.CompleteRequest
	9,  // 74: mcp.ModelContextProtocol.Ping:input_type -> mcp.PingRequest
	2,  // 75: mcp.ModelContextProtocol.Initialize:output_type -> mcp.InitializeResult
	6,  // 76: mcp.ModelContextProtocol.CallMethod:output_type -> mcp.CallToolResult
	4,  // 77: mcp.ModelContextProtocol.ListTools:output_type -> mcp.ListToolsResult
	12, // 78: mcp.ModelContextProtocol.ListPrompts:output_type -> mcp.ListPromptsResult
	14, // 79: mcp.ModelContextProtocol.GetPrompt:output_type -> mcp.GetPromptResult
	8,  // 80: mcp.ModelContextProtocol.Complete:output_type -> mcp.CompleteResult
	10, // 81: mcp.ModelContextProtocol.Ping:output_type -> mcp.PingResult
	75, // [75:82] is the sub-list for method output_type
	68, // [68:75] is the sub-list for method input_type
	68, // [68:68] is the sub-list for extension type_name
	68, // [68:68] is the sub-list for extension extendee
	0,  // [0:68] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	file_mcp_proto_msgTypes[1].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[2].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[3].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[4].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[5].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[10].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[11].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[12].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[13].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[14].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[17].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[18].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[19].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[20].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[21].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[22].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[23].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[25].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[26].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
		(*ContentBlock_Audio)(nil),
		(*ContentBlock_ResourceLink)(nil),
		(*ContentBlock_EmbeddedResource)(nil),
	}
	file_mcp_proto_msgTypes[27].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[28].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[29].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[31].OneofWrappers = []any{
		(*EmbeddedResource_TextResource)(nil),
		(*EmbeddedResource_BlobResource)(nil),
	}
	file_mcp_proto_msgTypes[32].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[33].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[34].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[35].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[36].OneofWrappers = []any{
		(*Reference_Prompt)(nil),
		(*Reference_ResourceTemplate)(nil),
	}
	file_mcp_proto_msgTypes[41].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		EnumInfos:         file_mcp_proto_enumTypes,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
