// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: mcp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_USER             Role = 1
	Role_ASSISTANT        Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "USER",
		2: "ASSISTANT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"USER":             1,
		"ASSISTANT":        2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

type CallToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,2,opt,name=arguments,proto3,oneof" json:"arguments,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CallToolRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type CallToolResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Content           []*ContentBlock        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	StructuredContent *structpb.Struct       `protobuf:"bytes,2,opt,name=structured_content,json=structuredContent,proto3,oneof" json:"structured_content,omitempty"`
	IsError           *bool                  `protobuf:"varint,3,opt,name=is_error,json=isError,proto3,oneof" json:"is_error,omitempty"`
	XMeta             *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CallToolResult) Reset() {
	*x = CallToolResult{}
	mi := &file_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResult) ProtoMessage() {}

func (x *CallToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResult.ProtoReflect.Descriptor instead.
func (*CallToolResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *CallToolResult) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CallToolResult) GetStructuredContent() *structpb.Struct {
	if x != nil {
		return x.StructuredContent
	}
	return nil
}

func (x *CallToolResult) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

func (x *CallToolResult) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,2,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ListToolsRequest) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ListToolsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResult) Reset() {
	*x = ListToolsResult{}
	mi := &file_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResult) ProtoMessage() {}

func (x *ListToolsResult) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResult.ProtoReflect.Descriptor instead.
func (*ListToolsResult) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResult) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ListToolsResult) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *ListToolsResult) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type WatchToolListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchToolListRequest) Reset() {
	*x = WatchToolListRequest{}
	mi := &file_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchToolListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchToolListRequest) ProtoMessage() {}

func (x *WatchToolListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchToolListRequest.ProtoReflect.Descriptor instead.
func (*WatchToolListRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{4}
}

type ToolListChangedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolListChangedNotification) Reset() {
	*x = ToolListChangedNotification{}
	mi := &file_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolListChangedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolListChangedNotification) ProtoMessage() {}

func (x *ToolListChangedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolListChangedNotification.ProtoReflect.Descriptor instead.
func (*ToolListChangedNotification) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{5}
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BaseMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema  *structpb.Struct       `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3,oneof" json:"output_schema,omitempty"`
	Annotations   *ToolAnnotations       `protobuf:"bytes,5,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,6,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *Tool) GetMetadata() *BaseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Tool) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Tool) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *Tool) GetOutputSchema() *structpb.Struct {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *Tool) GetAnnotations() *ToolAnnotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Tool) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ToolAnnotations struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ReadOnlyHint    *bool                  `protobuf:"varint,2,opt,name=read_only_hint,json=readOnlyHint,proto3,oneof" json:"read_only_hint,omitempty"`
	DestructiveHint *bool                  `protobuf:"varint,3,opt,name=destructive_hint,json=destructiveHint,proto3,oneof" json:"destructive_hint,omitempty"`
	IdempotentHint  *bool                  `protobuf:"varint,4,opt,name=idempotent_hint,json=idempotentHint,proto3,oneof" json:"idempotent_hint,omitempty"`
	OpenWorldHint   *bool                  `protobuf:"varint,5,opt,name=open_world_hint,json=openWorldHint,proto3,oneof" json:"open_world_hint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolAnnotations) Reset() {
	*x = ToolAnnotations{}
	mi := &file_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolAnnotations) ProtoMessage() {}

func (x *ToolAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolAnnotations.ProtoReflect.Descriptor instead.
func (*ToolAnnotations) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *ToolAnnotations) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ToolAnnotations) GetReadOnlyHint() bool {
	if x != nil && x.ReadOnlyHint != nil {
		return *x.ReadOnlyHint
	}
	return false
}

func (x *ToolAnnotations) GetDestructiveHint() bool {
	if x != nil && x.DestructiveHint != nil {
		return *x.DestructiveHint
	}
	return false
}

func (x *ToolAnnotations) GetIdempotentHint() bool {
	if x != nil && x.IdempotentHint != nil {
		return *x.IdempotentHint
	}
	return false
}

func (x *ToolAnnotations) GetOpenWorldHint() bool {
	if x != nil && x.OpenWorldHint != nil {
		return *x.OpenWorldHint
	}
	return false
}

type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ContentType:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	//	*ContentBlock_Audio
	//	*ContentBlock_ResourceLink
	//	*ContentBlock_EmbeddedResource
	ContentType   isContentBlock_ContentType `protobuf_oneof:"content_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_mcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{8}
}

func (x *ContentBlock) GetContentType() isContentBlock_ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *ContentBlock) GetText() *TextContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlock) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentBlock) GetAudio() *AudioContent {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ContentBlock) GetResourceLink() *ResourceLink {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_ResourceLink); ok {
			return x.ResourceLink
		}
	}
	return nil
}

func (x *ContentBlock) GetEmbeddedResource() *EmbeddedResource {
	if x != nil {
		if x, ok := x.ContentType.(*ContentBlock_EmbeddedResource); ok {
			return x.EmbeddedResource
		}
	}
	return nil
}

type isContentBlock_ContentType interface {
	isContentBlock_ContentType()
}

type ContentBlock_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type ContentBlock_Audio struct {
	Audio *AudioContent `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

type ContentBlock_ResourceLink struct {
	ResourceLink *ResourceLink `protobuf:"bytes,4,opt,name=resource_link,json=resourceLink,proto3,oneof"`
}

type ContentBlock_EmbeddedResource struct {
	EmbeddedResource *EmbeddedResource `protobuf:"bytes,5,opt,name=embedded_resource,json=embeddedResource,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_ContentType() {}

func (*ContentBlock_Image) isContentBlock_ContentType() {}

func (*ContentBlock_Audio) isContentBlock_ContentType() {}

func (*ContentBlock_ResourceLink) isContentBlock_ContentType() {}

func (*ContentBlock_EmbeddedResource) isContentBlock_ContentType() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,2,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_mcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{9}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *TextContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,3,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_mcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{10}
}

func (x *ImageContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ImageContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type AudioContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,3,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_mcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{11}
}

func (x *AudioContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AudioContent) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AudioContent) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type ResourceLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLink) Reset() {
	*x = ResourceLink{}
	mi := &file_mcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLink) ProtoMessage() {}

func (x *ResourceLink) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLink.ProtoReflect.Descriptor instead.
func (*ResourceLink) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceLink) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type EmbeddedResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResourceContents:
	//
	//	*EmbeddedResource_TextResource
	//	*EmbeddedResource_BlobResource
	ResourceContents isEmbeddedResource_ResourceContents `protobuf_oneof:"resource_contents"`
	Annotations      *Annotations                        `protobuf:"bytes,3,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	XMeta            *structpb.Struct                    `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmbeddedResource) Reset() {
	*x = EmbeddedResource{}
	mi := &file_mcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedResource) ProtoMessage() {}

func (x *EmbeddedResource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedResource.ProtoReflect.Descriptor instead.
func (*EmbeddedResource) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{13}
}

func (x *EmbeddedResource) GetResourceContents() isEmbeddedResource_ResourceContents {
	if x != nil {
		return x.ResourceContents
	}
	return nil
}

func (x *EmbeddedResource) GetTextResource() *TextResourceContents {
	if x != nil {
		if x, ok := x.ResourceContents.(*EmbeddedResource_TextResource); ok {
			return x.TextResource
		}
	}
	return nil
}

func (x *EmbeddedResource) GetBlobResource() *BlobResourceContents {
	if x != nil {
		if x, ok := x.ResourceContents.(*EmbeddedResource_BlobResource); ok {
			return x.BlobResource
		}
	}
	return nil
}

func (x *EmbeddedResource) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *EmbeddedResource) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type isEmbeddedResource_ResourceContents interface {
	isEmbeddedResource_ResourceContents()
}

type EmbeddedResource_TextResource struct {
	TextResource *TextResourceContents `protobuf:"bytes,1,opt,name=text_resource,json=textResource,proto3,oneof"`
}

type EmbeddedResource_BlobResource struct {
	BlobResource *BlobResourceContents `protobuf:"bytes,2,opt,name=blob_resource,json=blobResource,proto3,oneof"`
}

func (*EmbeddedResource_TextResource) isEmbeddedResource_ResourceContents() {}

func (*EmbeddedResource_BlobResource) isEmbeddedResource_ResourceContents() {}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BaseMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	MimeType      *string                `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Annotations   *Annotations           `protobuf:"bytes,5,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	Size          *int64                 `protobuf:"varint,6,opt,name=size,proto3,oneof" json:"size,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,7,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_mcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{14}
}

func (x *Resource) GetMetadata() *BaseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Resource) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *Resource) GetAnnotations() *Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Resource) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Resource) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type TextResourceContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	MimeType      *string                `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResourceContents) Reset() {
	*x = TextResourceContents{}
	mi := &file_mcp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResourceContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResourceContents) ProtoMessage() {}

func (x *TextResourceContents) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResourceContents.ProtoReflect.Descriptor instead.
func (*TextResourceContents) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{15}
}

func (x *TextResourceContents) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TextResourceContents) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *TextResourceContents) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResourceContents) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type BlobResourceContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	MimeType      *string                `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Blob          []byte                 `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	XMeta         *structpb.Struct       `protobuf:"bytes,4,opt,name=_meta,json=Meta,proto3,oneof" json:"_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobResourceContents) Reset() {
	*x = BlobResourceContents{}
	mi := &file_mcp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobResourceContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobResourceContents) ProtoMessage() {}

func (x *BlobResourceContents) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobResourceContents.ProtoReflect.Descriptor instead.
func (*BlobResourceContents) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{16}
}

func (x *BlobResourceContents) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *BlobResourceContents) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *BlobResourceContents) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *BlobResourceContents) GetXMeta() *structpb.Struct {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type BaseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMetadata) Reset() {
	*x = BaseMetadata{}
	mi := &file_mcp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMetadata) ProtoMessage() {}

func (x *BaseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMetadata.ProtoReflect.Descriptor instead.
func (*BaseMetadata) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{17}
}

func (x *BaseMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseMetadata) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type Annotations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      []Role                 `protobuf:"varint,1,rep,packed,name=audience,proto3,enum=mcp.Role" json:"audience,omitempty"`
	Priority      *float32               `protobuf:"fixed32,2,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	LastModified  *string                `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3,oneof" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotations) Reset() {
	*x = Annotations{}
	mi := &file_mcp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotations) ProtoMessage() {}

func (x *Annotations) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotations.ProtoReflect.Descriptor instead.
func (*Annotations) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{18}
}

func (x *Annotations) GetAudience() []Role {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *Annotations) GetPriority() float32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *Annotations) GetLastModified() string {
	if x != nil && x.LastModified != nil {
		return *x.LastModified
	}
	return ""
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x03mcp\x1a\x1cgoogle/protobuf/struct.proto\"\xac\x01\n" +
	"\x0fCallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\targuments\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\f\n" +
	"\n" +
	"_argumentsB\b\n" +
	"\x06X_meta\"\x8b\x02\n" +
	"\x0eCallToolResult\x12+\n" +
	"\acontent\x18\x01 \x03(\v2\x11.mcp.ContentBlockR\acontent\x12K\n" +
	"\x12structured_content\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x11structuredContent\x88\x01\x01\x12\x1e\n" +
	"\bis_error\x18\x03 \x01(\bH\x01R\aisError\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x02R\x04Meta\x88\x01\x01B\x15\n" +
	"\x13_structured_contentB\v\n" +
	"\t_is_errorB\b\n" +
	"\x06X_meta\"w\n" +
	"\x10ListToolsRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\t\n" +
	"\a_cursorB\b\n" +
	"\x06X_meta\"\xa5\x01\n" +
	"\x0fListToolsResult\x12\x1f\n" +
	"\x05tools\x18\x01 \x03(\v2\t.mcp.ToolR\x05tools\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_next_cursorB\b\n" +
	"\x06X_meta\"\x16\n" +
	"\x14WatchToolListRequest\"\x1d\n" +
	"\x1bToolListChangedNotification\"\x87\x03\n" +
	"\x04Tool\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.mcp.BaseMetadataR\bmetadata\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12A\n" +
	"\routput_schema\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\foutputSchema\x88\x01\x01\x12;\n" +
	"\vannotations\x18\x05 \x01(\v2\x14.mcp.ToolAnnotationsH\x02R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_output_schemaB\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xbc\x02\n" +
	"\x0fToolAnnotations\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12)\n" +
	"\x0eread_only_hint\x18\x02 \x01(\bH\x01R\freadOnlyHint\x88\x01\x01\x12.\n" +
	"\x10destructive_hint\x18\x03 \x01(\bH\x02R\x0fdestructiveHint\x88\x01\x01\x12,\n" +
	"\x0fidempotent_hint\x18\x04 \x01(\bH\x03R\x0eidempotentHint\x88\x01\x01\x12+\n" +
	"\x0fopen_world_hint\x18\x05 \x01(\bH\x04R\ropenWorldHint\x88\x01\x01B\b\n" +
	"\x06_titleB\x11\n" +
	"\x0f_read_only_hintB\x13\n" +
	"\x11_destructive_hintB\x12\n" +
	"\x10_idempotent_hintB\x12\n" +
	"\x10_open_world_hint\"\x9c\x02\n" +
	"\fContentBlock\x12&\n" +
	"\x04text\x18\x01 \x01(\v2\x10.mcp.TextContentH\x00R\x04text\x12)\n" +
	"\x05image\x18\x02 \x01(\v2\x11.mcp.ImageContentH\x00R\x05image\x12)\n" +
	"\x05audio\x18\x03 \x01(\v2\x11.mcp.AudioContentH\x00R\x05audio\x128\n" +
	"\rresource_link\x18\x04 \x01(\v2\x11.mcp.ResourceLinkH\x00R\fresourceLink\x12D\n" +
	"\x11embedded_resource\x18\x05 \x01(\v2\x15.mcp.EmbeddedResourceH\x00R\x10embeddedResourceB\x0e\n" +
	"\fcontent_type\"\xa7\x01\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x127\n" +
	"\vannotations\x18\x02 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xc5\x01\n" +
	"\fImageContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x127\n" +
	"\vannotations\x18\x03 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xc5\x01\n" +
	"\fAudioContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x127\n" +
	"\vannotations\x18\x03 \x01(\v2\x10.mcp.AnnotationsH\x00R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"9\n" +
	"\fResourceLink\x12)\n" +
	"\bresource\x18\x01 \x01(\v2\r.mcp.ResourceR\bresource\"\xb1\x02\n" +
	"\x10EmbeddedResource\x12@\n" +
	"\rtext_resource\x18\x01 \x01(\v2\x19.mcp.TextResourceContentsH\x00R\ftextResource\x12@\n" +
	"\rblob_resource\x18\x02 \x01(\v2\x19.mcp.BlobResourceContentsH\x00R\fblobResource\x127\n" +
	"\vannotations\x18\x03 \x01(\v2\x10.mcp.AnnotationsH\x01R\vannotations\x88\x01\x01\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x02R\x04Meta\x88\x01\x01B\x13\n" +
	"\x11resource_contentsB\x0e\n" +
	"\f_annotationsB\b\n" +
	"\x06X_meta\"\xda\x02\n" +
	"\bResource\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.mcp.BaseMetadataR\bmetadata\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\tmime_type\x18\x04 \x01(\tH\x01R\bmimeType\x88\x01\x01\x127\n" +
	"\vannotations\x18\x05 \x01(\v2\x10.mcp.AnnotationsH\x02R\vannotations\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x06 \x01(\x03H\x03R\x04size\x88\x01\x01\x121\n" +
	"\x05_meta\x18\a \x01(\v2\x17.google.protobuf.StructH\x04R\x04Meta\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_mime_typeB\x0e\n" +
	"\f_annotationsB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06X_meta\"\xa9\x01\n" +
	"\x14TextResourceContents\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12 \n" +
	"\tmime_type\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\f\n" +
	"\n" +
	"_mime_typeB\b\n" +
	"\x06X_meta\"\xa9\x01\n" +
	"\x14BlobResourceContents\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12 \n" +
	"\tmime_type\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x12\n" +
	"\x04blob\x18\x03 \x01(\fR\x04blob\x121\n" +
	"\x05_meta\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x01R\x04Meta\x88\x01\x01B\f\n" +
	"\n" +
	"_mime_typeB\b\n" +
	"\x06X_meta\"G\n" +
	"\fBaseMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title\"\x9e\x01\n" +
	"\vAnnotations\x12%\n" +
	"\baudience\x18\x01 \x03(\x0e2\t.mcp.RoleR\baudience\x12\x1f\n" +
	"\bpriority\x18\x02 \x01(\x02H\x00R\bpriority\x88\x01\x01\x12(\n" +
	"\rlast_modified\x18\x03 \x01(\tH\x01R\flastModified\x88\x01\x01B\v\n" +
	"\t_priorityB\x10\n" +
	"\x0e_last_modified*5\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tASSISTANT\x10\x022\xd7\x01\n" +
	"\x14ModelContextProtocol\x125\n" +
	"\bCallTool\x12\x14.mcp.CallToolRequest\x1a\x13.mcp.CallToolResult\x128\n" +
	"\tListTools\x12\x15.mcp.ListToolsRequest\x1a\x14.mcp.ListToolsResult\x12N\n" +
	"\rWatchToolList\x12\x19.mcp.WatchToolListRequest\x1a .mcp.ToolListChangedNotification0\x01B\rZ\vgrpc2mcp/pbb\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_mcp_proto_goTypes = []any{
	(Role)(0),                           // 0: mcp.Role
	(*CallToolRequest)(nil),             // 1: mcp.CallToolRequest
	(*CallToolResult)(nil),              // 2: mcp.CallToolResult
	(*ListToolsRequest)(nil),            // 3: mcp.ListToolsRequest
	(*ListToolsResult)(nil),             // 4: mcp.ListToolsResult
	(*WatchToolListRequest)(nil),        // 5: mcp.WatchToolListRequest
	(*ToolListChangedNotification)(nil), // 6: mcp.ToolListChangedNotification
	(*Tool)(nil),                        // 7: mcp.Tool
	(*ToolAnnotations)(nil),             // 8: mcp.ToolAnnotations
	(*ContentBlock)(nil),                // 9: mcp.ContentBlock
	(*TextContent)(nil),                 // 10: mcp.TextContent
	(*ImageContent)(nil),                // 11: mcp.ImageContent
	(*AudioContent)(nil),                // 12: mcp.AudioContent
	(*ResourceLink)(nil),                // 13: mcp.ResourceLink
	(*EmbeddedResource)(nil),            // 14: mcp.EmbeddedResource
	(*Resource)(nil),                    // 15: mcp.Resource
	(*TextResourceContents)(nil),        // 16: mcp.TextResourceContents
	(*BlobResourceContents)(nil),        // 17: mcp.BlobResourceContents
	(*BaseMetadata)(nil),                // 18: mcp.BaseMetadata
	(*Annotations)(nil),                 // 19: mcp.Annotations
	(*structpb.Struct)(nil),             // 20: google.protobuf.Struct
}
var file_mcp_proto_depIdxs = []int32{
	20, // 0: mcp.CallToolRequest.arguments:type_name -> google.protobuf.Struct
	20, // 1: mcp.CallToolRequest._meta:type_name -> google.protobuf.Struct
	9,  // 2: mcp.CallToolResult.content:type_name -> mcp.ContentBlock
	20, // 3: mcp.CallToolResult.structured_content:type_name -> google.protobuf.Struct
	20, // 4: mcp.CallToolResult._meta:type_name -> google.protobuf.Struct
	20, // 5: mcp.ListToolsRequest._meta:type_name -> google.protobuf.Struct
	7,  // 6: mcp.ListToolsResult.tools:type_name -> mcp.Tool
	20, // 7: mcp.ListToolsResult._meta:type_name -> google.protobuf.Struct
	18, // 8: mcp.Tool.metadata:type_name -> mcp.BaseMetadata
	20, // 9: mcp.Tool.input_schema:type_name -> google.protobuf.Struct
	20, // 10: mcp.Tool.output_schema:type_name -> google.protobuf.Struct
	8,  // 11: mcp.Tool.annotations:type_name -> mcp.ToolAnnotations
	20, // 12: mcp.Tool._meta:type_name -> google.protobuf.Struct
	10, // 13: mcp.ContentBlock.text:type_name -> mcp.TextContent
	11, // 14: mcp.ContentBlock.image:type_name -> mcp.ImageContent
	12, // 15: mcp.ContentBlock.audio:type_name -> mcp.AudioContent
	13, // 16: mcp.ContentBlock.resource_link:type_name -> mcp.ResourceLink
	14, // 17: mcp.ContentBlock.embedded_resource:type_name -> mcp.EmbeddedResource
	19, // 18: mcp.TextContent.annotations:type_name -> mcp.Annotations
	20, // 19: mcp.TextContent._meta:type_name -> google.protobuf.Struct
	19, // 20: mcp.ImageContent.annotations:type_name -> mcp.Annotations
	20, // 21: mcp.ImageContent._meta:type_name -> google.protobuf.Struct
	19, // 22: mcp.AudioContent.annotations:type_name -> mcp.Annotations
	20, // 23: mcp.AudioContent._meta:type_name -> google.protobuf.Struct
	15, // 24: mcp.ResourceLink.resource:type_name -> mcp.Resource
	16, // 25: mcp.EmbeddedResource.text_resource:type_name -> mcp.TextResourceContents
	17, // 26: mcp.EmbeddedResource.blob_resource:type_name -> mcp.BlobResourceContents
	19, // 27: mcp.EmbeddedResource.annotations:type_name -> mcp.Annotations
	20, // 28: mcp.EmbeddedResource._meta:type_name -> google.protobuf.Struct
	18, // 29: mcp.Resource.metadata:type_name -> mcp.BaseMetadata
	19, // 30: mcp.Resource.annotations:type_name -> mcp.Annotations
	20, // 31: mcp.Resource._meta:type_name -> google.protobuf.Struct
	20, // 32: mcp.TextResourceContents._meta:type_name -> google.protobuf.Struct
	20, // 33: mcp.BlobResourceContents._meta:type_name -> google.protobuf.Struct
	0,  // 34: mcp.Annotations.audience:type_name -> mcp.Role
	1,  // 35: mcp.ModelContextProtocol.CallTool:input_type -> mcp.CallToolRequest
	3,  // 36: mcp.ModelContextProtocol.ListTools:input_type -> mcp.ListToolsRequest
	5,  // 37: mcp.ModelContextProtocol.WatchToolList:input_type -> mcp.WatchToolListRequest
	2,  // 38: mcp.ModelContextProtocol.CallTool:output_type -> mcp.CallToolResult
	4,  // 39: mcp.ModelContextProtocol.ListTools:output_type -> mcp.ListToolsResult
	6,  // 40: mcp.ModelContextProtocol.WatchToolList:output_type -> mcp.ToolListChangedNotification
	38, // [38:41] is the sub-list for method output_type
	35, // [35:38] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	file_mcp_proto_msgTypes[0].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[1].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[2].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[3].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[6].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[7].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[8].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
		(*ContentBlock_Audio)(nil),
		(*ContentBlock_ResourceLink)(nil),
		(*ContentBlock_EmbeddedResource)(nil),
	}
	file_mcp_proto_msgTypes[9].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[10].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[11].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[13].OneofWrappers = []any{
		(*EmbeddedResource_TextResource)(nil),
		(*EmbeddedResource_BlobResource)(nil),
	}
	file_mcp_proto_msgTypes[14].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[15].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[16].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[17].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		EnumInfos:         file_mcp_proto_enumTypes,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
