// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mcp.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelContextProtocol_Initialize_FullMethodName = "/mcp.ModelContextProtocol/Initialize"
	ModelContextProtocol_CallMethod_FullMethodName = "/mcp.ModelContextProtocol/CallMethod"
	ModelContextProtocol_ListTools_FullMethodName  = "/mcp.ModelContextProtocol/ListTools"
)

// ModelContextProtocolClient is the client API for ModelContextProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelContextProtocolClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResult, error)
	CallMethod(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResult, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResult, error)
}

type modelContextProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewModelContextProtocolClient(cc grpc.ClientConnInterface) ModelContextProtocolClient {
	return &modelContextProtocolClient{cc}
}

func (c *modelContextProtocolClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResult)
	err := c.cc.Invoke(ctx, ModelContextProtocol_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelContextProtocolClient) CallMethod(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResult)
	err := c.cc.Invoke(ctx, ModelContextProtocol_CallMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelContextProtocolClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResult)
	err := c.cc.Invoke(ctx, ModelContextProtocol_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelContextProtocolServer is the server API for ModelContextProtocol service.
// All implementations should embed UnimplementedModelContextProtocolServer
// for forward compatibility.
type ModelContextProtocolServer interface {
	Initialize(context.Context, *InitializeRequest) (*InitializeResult, error)
	CallMethod(context.Context, *CallToolRequest) (*CallToolResult, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResult, error)
}

// UnimplementedModelContextProtocolServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelContextProtocolServer struct{}

func (UnimplementedModelContextProtocolServer) Initialize(context.Context, *InitializeRequest) (*InitializeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedModelContextProtocolServer) CallMethod(context.Context, *CallToolRequest) (*CallToolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallMethod not implemented")
}
func (UnimplementedModelContextProtocolServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedModelContextProtocolServer) testEmbeddedByValue() {}

// UnsafeModelContextProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelContextProtocolServer will
// result in compilation errors.
type UnsafeModelContextProtocolServer interface {
	mustEmbedUnimplementedModelContextProtocolServer()
}

func RegisterModelContextProtocolServer(s grpc.ServiceRegistrar, srv ModelContextProtocolServer) {
	// If the following call pancis, it indicates UnimplementedModelContextProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelContextProtocol_ServiceDesc, srv)
}

func _ModelContextProtocol_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelContextProtocolServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelContextProtocol_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelContextProtocolServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelContextProtocol_CallMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelContextProtocolServer).CallMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelContextProtocol_CallMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelContextProtocolServer).CallMethod(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelContextProtocol_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelContextProtocolServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelContextProtocol_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelContextProtocolServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelContextProtocol_ServiceDesc is the grpc.ServiceDesc for ModelContextProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelContextProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.ModelContextProtocol",
	HandlerType: (*ModelContextProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ModelContextProtocol_Initialize_Handler,
		},
		{
			MethodName: "CallMethod",
			Handler:    _ModelContextProtocol_CallMethod_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ModelContextProtocol_ListTools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcp.proto",
}
